spring:
  datasource:
    druid:
      url: jdbc:mysql://${ip:port/databaseName}?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
      username: ${username}
      password: ${加密后的password}
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey};druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #启用ConfigFilter
      filter:
        config:
          enabled: true
      #配置初始化大小、最小、最大
      initial-size: 5
      min-idle: 5
      max-active: 10
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      #自动连接测试
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      #打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      #配置监控统计拦截的filters
      filters: stat,wall,slf4j
      #配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        #IP白名单(没有配置或者为空，则允许所有访问)
        allow: 
        #IP黑名单 (存在共同时，deny优先于allow)
        deny: 
        #禁用HTML页面上的“Reset All”功能
        reset-enable: false
        #登录名
        #login-username: ${username}
        #登录密码
        #login-password: ${password}
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: true
  activemq:
    broker-url: tcp://localhost:61616
    #不使用Spring Boot内部的ActiveMQ，连接我们自己的MQ服务器
    in-memory: false
    #是否在重新传递来自回滚事务的消息之前停止消息传递。这意味着启用此功能时不会保留消息顺序。
    non-blocking-redelivery: false
    #等待发送消息超时，0为无限制
    send-timeout: 0
    user: admin
    password: 123456
  #是否启用发布订阅模式（这里不启用，使用配置类让双模式并存）
  jms:
    pub-sub-domain: false
    
#口袋48配置
pocket48:
  username: ${username}
  password: ${password}
  
#酷Q配置
kuq:
  enabled: false
  bot-name: Bot01
  post-url: ${酷Q的IP}
  post-port: ${酷Q的端口}
  socket-port: ${自己应用的端口}
  log-path: null
  admin-id: ${QQ号}

#redis配置
redis:
  url: 127.0.0.1:6379
  timeout: 10000